<?php
if ( ! defined( 'ABSPATH') ) { exit; }
if(AEW_TOKEN == '') { 
	echo __('Your token is no set, please contact with support service.','aliexpress');
	return;
}
$_product = wc_get_product($post);
require_once(AEW_AE_PATH . 'AEFactory.php');
echo '<table class="form-table">';
$factory = new AEFactory(AEW_TOKEN);
$st = $factory->get_shipping_templates();
$productAliExpress = get_post_meta($post->ID, '_aew_product_id',true);
$shippingTemplateProduct = get_post_meta($post->ID,'_aew_shipping_template_product', true);

$groups = $factory->wrapper->get_product_groups();
if(!$productAliExpress or $productAliExpress == '0' or $productAliExpress == '') {
    echo '';
}else{
	$statusAE = '0';
	$statusAE = get_post_meta($post->ID, '_aew_status_ae', true);
	if(!$statusAE){
		$statusAE = '0';
	}

	?>
			<?php if(get_post_meta($post->ID, '_aew_run_job', true) and get_post_meta($post->ID, '_aew_run_job', true) != "0") { ?>

				<tr valign="top" class="remove_when_id">
					<th scope="row"><?=__('Remove Job', 'aliexpress')?>
					<p class="description"><?= __('Eliminates the blocking of the product generated by a job.','aliexpress') ?></p>
					</th>
					<td><a href="<?=admin_url('admin-ajax.php?action=aew_remove_run_job')?>&id=<?=$post->ID?>" class="button"><?=__('Remove Job','aliexpress')?></a></td>
				</tr>

				<?php } ?>
			<tr valign="top" class="remove_when_id">
				<th scope="row"><?=__('Product ID on AliExpress', 'aliexpress')?>
				<a class="button removeProductID" data-id="<?=$post->ID?>"><?=__('Remove AliExpress Product ID','aliexpress')?></a>
				</th>
				<td><?=$productAliExpress?> <a class="aew_view" href="https://www.aliexpress.com/item/<?=$productAliExpress?>.html" target="_blank"><?=__('View Product on AliExpress','aliexpress')?></a></td>
			</tr>
			<tr valign="top" class="remove_when_id">
				<th scope="row"><?=__('Actions', 'aliexpress')?>
                <p class="description"><?= __('Actions for AliExpress product','aliexpress') ?></p>
				</th>
				<td>
					<?php if($statusAE == '1') { ?>
						<a class="boton_actions_products" style="background-color:orange;" href="javascript:aew_disable_products('<?=$productAliExpress?>', true);"><?=__('Disable Product','aliexpress');?></a>
					<?php }else{ ?>
						<a class="boton_actions_products" style="background-color:green;" href="javascript:aew_active_products('<?=$productAliExpress?>', true);"><?=__('Activate Product','aliexpress');?></a>
					<?php } ?>
						<a class="boton_actions_products" style="background-color:red;" href="javascript:aew_delete_products('<?=$productAliExpress?>', true);"><?=__('Delete Product','aliexpress');?></a>
				</td>
			</tr>
			
	
	<?php
}

$categorias = AEW_Category::show_categories_to_mapping(null, true);
$available_cats = array();
foreach($categorias as $cat) {
	$available_cats[] = $cat->term_id;
}
$active = get_post_meta($post->ID, '_aew_default_category_id', true);
?>
<tr valign="top">
				<th scope="row"><?=__('Choose default Category', 'aliexpress')?>
				<p class="description"><?= __('First select the product categories, the ones that are mapped will appear here.','aliexpress') ?></p>
				</th>
				<td>
					<select id="aew_category_id" name="aew_category_id" >
						<option value="0"><?=__('Choose default Category', 'aliexpress')?></option>
					</select>
				</td>
			</tr>
			<tr>
				<th><?=__('Shipping Template', 'aliexpress')?>
				<p class="description"><?=__('You can override the shipping template, if you use default, AliExpress use the category shipping template, if category use default, using global.','aliexpress')?></p>
				</th>
				<td><?=AEW_Category::get_select_shipping_templates_category($st, $shippingTemplateProduct)?></td>
			</tr>
			<tr>
				<th><?=__('Group', 'aliexpress')?></th>
				<td><?php
				$groupSelected = get_post_meta($post->ID,'aew_group_product', true);
                echo AEW_MAIN::select_group_category($groups,$groupSelected, "aew_group_select");
			?></td>
			</tr>
			<tr>
				<th><?=__('EAN Code', 'aliexpress')?></th>
				<td><?php
				$ean_ae = get_post_meta($post->ID,'aew_ean', true);
				?>
				<input type="text" value="<?=$ean_ae?>" name="aew_ean" />
			</td>
			</tr>
			<?php
				if($_product->is_type("variable")) {
					$explosionActive = get_post_meta($post->ID, '_aew_explosion_variations', true);
					?>
					<tr valign="top">
						<th scope="row"><?=__('Explosion of variations', 'aliexpress')?>
						<p class="description"><?= __('If the variations are complicated to map you can use this option to separate each variation into different products','aliexpress') ?></p></th>
						<td>
							<input type="checkbox" value="1" name="aew_explosion_variations" <?= checked("1", $explosionActive)?>/><?=__('Explosion of variations', 'aliexpress')?>
						</td>
					</tr>
			<?php } ?>
</table>
<script>
AEW_Default_Category = '<?=$active?>';
AEW_Available_Categories = <?=json_encode($available_cats)?>;
function reload_aew_categories() {
	jQuery("select#aew_category_id").html('<option value="0"><?=__('Choose default Category', 'aliexpress')?></option>');
	jQuery('#product_catchecklist  input:checked').each(function(i) {
		var totalCategoriesAE = jQuery('#product_catchecklist  input:checked').length;
		var id = jQuery(this).val();
		if(!AEW_Available_Categories.includes(parseInt(id))) {
			return;
		}
		var name = jQuery(this).parent("label").text();
		
		if(AEW_Default_Category == '') {
			console.log("seleccion auto");
			if(totalCategoriesAE == (i+1) ) {
				var selected = 'selected="selected"';
				console.log("selected auto ", i);
			}
		}else{
			if(AEW_Default_Category == id) {
				var selected = 'selected="selected"';
			}else{ var selected = ''; }
		}
		
		jQuery("select#aew_category_id").append('<option value="'+id+'" '+selected+'>'+name+'</option>');
	});
}
jQuery(document).on("click", "#product_catchecklist input", function(){
	reload_aew_categories();
});
reload_aew_categories();



</script>