ALIWOOLang = {
    'Wait': 'Wait...',
    'Upload': 'Upload',
    'Uploading' : 'Uploading...',
    'Updating': 'Updating...',
    'Update': 'Update',
    'SelectCategory': 'Select Category',
    'SelectThisCategory': 'Select Category',
    'AECategories': 'AliExpress Categories',
    'Unlink': 'Unlink',
    'CargandoCategories': 'Please Wait...',
    'AreYouSure': 'Are you sure?',
    'NoRevert': '',
    'YesDelete': 'Yes, Delete',
    'ChooseTerm': 'Choose Term',
    'Shipping': 'Shipping',
    'SelectProducts': 'Select Products',
    'SelectProductsSend': 'Select Products to send',
    'TrackingRequired': 'Tracking Number is required',
    'CustomValue': 'Custom Value',
    'seeLogError': 'See log error',
    'productsToAE': 'products send to AliExpress',
    'correct': 'Correct',
    'width': 'Width',
    'height': 'Height',
    'length': 'Length',
    'weight': 'Weight',
    'errorCategorySet': 'An error ocurred when set category',
    'norevert': 'This action can not be undone',
    'yesDelete': 'Yes, delete it',
    'orderImportOk': 'Order imported successfully',
    'orderImportError': 'An error occurred while importing the order',
    'chooseTerm': 'Choose term',
    'chooseOption': 'Choose an option',
    'useAlias': 'Use Alias',
    'useValue': 'Use Value',
    'shipping': 'Shipping',
    'selectProducts': 'Select Products',
    'selectProductsToSend': 'Mark which products will be sent',
    'TrakingRequire': 'Tracking number is required.',
    'TrakingIncorrect': 'The tracking number is incorrect, check the carrier',
    'jobFinished': 'Work Finished',
    'noUpdateJobFinished': 'Unable to update job status',
    "loading": 'Please wait...',
    "viewOrder": 'View Order',
    "clickHere": 'click here',
    "error": 'Error',
    "attrRepeat": 'Repeated Attributes',
    "emailorCallbackNoAvailable": 'The email is required',
    "errorRemoveCategoryAE": 'It was not possible to disconnect the category, try again',
    'idProductDelete': 'The product ID has removed',
    'urlTrackingRequired': 'Tracking Website is required',
    'noJobsPending': 'There are no pending jobs',
    'calculateProducts': 'Calculating products to eliminate',
    'sureDeleteProducts': 'This operation will permanently delete the products on AliExpress, confirm the action',
    'sureDisableProducts': 'This operation will disable the products on AliExpress, This action is not recommended to maintain product positioning. confirm the action',
    'sureActiveProducts': 'This operation will active the products on AliExpress, confirm the action',
    'CreatingWooCommerceProduct': 'Creating WooCommerce Product...',
    'viewProduct': 'View Product',
    'suggestCategory': 'Obtain category suggest',
    'selectOne': 'Select One',
    'editAEIdTitle': 'Edit AliExpress Id',
    'btEdit': 'Edit',
    'editAEIdNotFound': 'Product Id not found.',
    'editAEIdAlreadyMapped': 'The AliExpress Id is already mapped to another WooCommerce product',
    'cancel': 'Cancel',
    'search': 'search...'
}