ALIWOOLang = {
    'Wait': 'Espere...',
    'Upload': 'Subir',
    'Uploading' : 'Subiendo...',
    'Updating': 'Actualizando',
    'Update': 'Actualizar',
    'SelectCategory': 'Selecciona una Categoría',
    'SelectThisCategory': 'Selecionar Categoría',
    'AECategories': 'Categorías de AliExpress',
    'Unlink': 'Desconectar',
    'CargandoCategories': 'Por favor Espere...',
    'AreYouSure': 'Está Segur@?',
    'NoRevert': 'Esto no se puede deshacer',
    'YesDelete': 'Sí, Borrar',
    'ChooseTerm': 'Elija un término',
    'Shipping': 'Envio',
    'SelectProducts': 'Selecciona Producto/os',
    'SelectProductsSend': 'Selecciona productos para enviar',
    'TrackingRequired': 'El número de seguimiento es obligatorío',
    'CustomValue': 'Valor Personalizado',
    'seeLogError': 'Revise el Historial de Errores',
    'productsToAE': 'productos enviados a AliExpress',
    'correct': 'Correcto',
    'width': 'Ancho',
    'height': 'Alto',
    'length': 'Profundidad',
    'weight': 'Peso',
    'errorCategorySet': 'Ha ocurrido un error al establecer la categoría',
    'norevert': 'Esta acción no se puede deshacer',
    'yesDelete': 'Si, eliminar',
    'orderImportOk': 'Pedido Importado Correctamente',
    'orderImportError': 'Ha ocurrido un error al importar el pedido',
    'chooseTerm': 'Elija un término',
    'chooseOption': 'Elija una opción',
    'useAlias': 'Usar Alias',
    'useValue': 'Usar Valor',
    'shipping': 'Envío',
    'selectProducts': 'Seleccione los Productos',
    'selectProductsToSend': 'Marque que productos serán enviados',
    'TrakingRequire': 'El número de seguimiento es requerido',
    'TrakingIncorrect': 'El número de seguimiento es incorrecto, compruebe el transportista',
    'jobFinished': 'Trabajo Finalizado',
    'noUpdateJobFinished': 'No es posible actualizar su estado',
    "loading": 'Espere...',
    "viewOrder": 'Ver Pedido',
    "clickHere": 'clic aquí',
    "error": 'Error',
    "attrRepeat": 'Atributos repetidos',
    "emailorCallbackNoAvailable": 'El email es requerido',
    "errorRemoveCategoryAE": 'No ha sido posible desconectar la categoría, vuelva a intentarlo',
    'idProductDelete': 'El ID ha sido eliminado',
    'urlTrackingRequired': 'La URL de seguimiento es obligatoria',
    'noJobsPending': 'No existen trabajos pendientes',
    'calculateProducts': 'Calculando productos a eliminar...',
    'sureDeleteProducts': 'Esto eliminará todos los productos de AliExpress de esta categoría, ¿Confirma la acción?',
    'sureDisableProducts': 'Esto deshabilitará los productos de esta categoría en AliExpress, no se recomienda ya que puede perjudicar al posicionamiento de los productos. ¿Confirma la acción?',
    'sureActiveProducts': 'Esto activará los productos de esta categoría en AliExpress, ¿Confirma la acción?',
    'CreatingWooCommerceProduct': 'Creando producto WooCommerce',
    'viewProduct': 'Ver Producto',
    'suggestCategory': 'Obtener Categoria Sugerida',
    'selectOne': 'Seleccione una categoría',
    'editAEIdTitle': 'Editar Id de AliExpress',
    'btEdit': 'Editar',
    'editAEIdNotFound': 'El Id del producto no se ha encontrado.',
    'editAEIdAlreadyMapped': 'El Id del producto de AliExpress ya está mapeado a otro producto de WooCommerce',
    'cancel': 'Cancelar',
    'search': 'buscar...'
}