ALIWOOLang = {
    'Wait': 'Aspetta...',
    'Upload': 'Carica',
    'Uploading' : 'Caricando...',
    'Updating': 'Aggiornamento..',
    'Update': 'Aggiornare',
    'SelectCategory': 'Seleziona la Categoria',
    'SelectThisCategory': 'Seleziona Categoria',
    'AECategories': 'Categoria AliExpress',
    'Unlink': 'Scollegare',
    'CargandoCategories': 'Un momento, per favore...',
    'AreYouSure': 'Sei sicuro?',
    'NoRevert': '',
    'YesDelete': 'Si, cancella',
    'ChooseTerm': 'Scegli il termine',
    'Shipping': 'Spedizione',
    'SelectProducts': 'Seleziona i prodotti',
    'SelectProductsSend': 'Seleziona i prodotti da spedire',
    'TrackingRequired': 'È richiesto il Numero di Tracking',
    'CustomValue': 'Valore del Cliente',
    'seeLogError': 'Vedi la lista di errori',
    'productsToAE': 'Prodotti inviati da AliExpress',
    'correct': 'Corretto',
    'width': 'Larghezza',
    'height': 'Altezza',
    'length': 'Lunghezza',
    'weight': 'Peso',
    'errorCategorySet': 'Si è verificato un errore nella selezione della Categoria',
    'norevert': 'Questa azione non si puó essere annulata',
    'yesDelete': 'Si, cancella',
    'orderImportOk': 'Ordine importato con successo',
    'orderImportError': 'Si è verificato un errore importando l\'ordine',
    'chooseTerm': 'Scegli un termine',
    'chooseOption': 'Scegli un\'opzione' ,
    'useAlias': 'Usa Alias',
    'useValue': 'Usa un Valore',
    'shipping': 'Spedizione',
    'selectProducts': 'Seleziona Prodotti',
    'selectProductsToSend': 'Seleziona i prodotti che saranno spediti',
    'TrakingRequire': 'È richiesto il Numero di Tracking.',
    'TrakingIncorrect': 'Il numero Traking è sbagliato, verifica il corriere',
    'jobFinished': 'Compito finito',
    'noUpdateJobFinished': 'Impossibile aggiornare lo stato del compito',
    "loading": 'Un momento, per favore...',
    "viewOrder": 'Vedi Ordine',
    "clickHere": 'Clicca qui',
    "error": 'Errore',
    "attrRepeat": 'Attributi Ripetuti',
    "emailorCallbackNoAvailable": 'L\'email è richiesta',
    "errorRemoveCategoryAE": 'Non è stato possibile scollegare la categoria, prova di nuovo',
    'idProductDelete': 'La ID del prodotto è stata rimossa',
    'urlTrackingRequired': 'È richiesto il monitoraggio del sito Web',
    'noJobsPending': 'Non ci sono lavori in sospeso'
}